<?xml version="1.0" encoding="UTF-8" ?>
<Package name="Chokaigi2015" format_version="4">
    <Manifest src="manifest.xml" />
    <BehaviorDescriptions>
        <BehaviorDescription name="behavior" src="behavior_1" xar="behavior.xar" />
    </BehaviorDescriptions>
    <Dialogs />
    <Resources>
        <File name="index" src="html/index.html" />
        <File name=".bower" src="html/bower_components/angular-foundation-bower/.bower.json" />
        <File name="bower" src="html/bower_components/angular-foundation-bower/bower.json" />
        <File name="mm-foundation-tpls" src="html/bower_components/angular-foundation-bower/mm-foundation-tpls.js" />
        <File name="mm-foundation-tpls.min" src="html/bower_components/angular-foundation-bower/mm-foundation-tpls.min.js" />
        <File name="mm-foundation" src="html/bower_components/angular-foundation-bower/mm-foundation.js" />
        <File name="mm-foundation.min" src="html/bower_components/angular-foundation-bower/mm-foundation.min.js" />
        <File name=".bower" src="html/bower_components/angular-mocks/.bower.json" />
        <File name="README" src="html/bower_components/angular-mocks/README.md" />
        <File name="angular-mocks" src="html/bower_components/angular-mocks/angular-mocks.js" />
        <File name="bower" src="html/bower_components/angular-mocks/bower.json" />
        <File name="ngAnimateMock" src="html/bower_components/angular-mocks/ngAnimateMock.js" />
        <File name="ngMock" src="html/bower_components/angular-mocks/ngMock.js" />
        <File name="ngMockE2E" src="html/bower_components/angular-mocks/ngMockE2E.js" />
        <File name="package" src="html/bower_components/angular-mocks/package.json" />
        <File name=".bower" src="html/bower_components/angular-sanitize/.bower.json" />
        <File name="README" src="html/bower_components/angular-sanitize/README.md" />
        <File name="angular-sanitize" src="html/bower_components/angular-sanitize/angular-sanitize.js" />
        <File name="angular-sanitize.min" src="html/bower_components/angular-sanitize/angular-sanitize.min.js" />
        <File name="angular-sanitize.min.js" src="html/bower_components/angular-sanitize/angular-sanitize.min.js.map" />
        <File name="bower" src="html/bower_components/angular-sanitize/bower.json" />
        <File name="index" src="html/bower_components/angular-sanitize/index.js" />
        <File name="package" src="html/bower_components/angular-sanitize/package.json" />
        <File name=".bower" src="html/bower_components/angular-scenario/.bower.json" />
        <File name="README" src="html/bower_components/angular-scenario/README.md" />
        <File name="angular-scenario" src="html/bower_components/angular-scenario/angular-scenario.js" />
        <File name="bower" src="html/bower_components/angular-scenario/bower.json" />
        <File name="jstd-scenario-adapter-config" src="html/bower_components/angular-scenario/jstd-scenario-adapter-config.js" />
        <File name="jstd-scenario-adapter" src="html/bower_components/angular-scenario/jstd-scenario-adapter.js" />
        <File name="package" src="html/bower_components/angular-scenario/package.json" />
        <File name=".bower" src="html/bower_components/angular-ui-router/.bower.json" />
        <File name="CHANGELOG" src="html/bower_components/angular-ui-router/CHANGELOG.md" />
        <File name="CONTRIBUTING" src="html/bower_components/angular-ui-router/CONTRIBUTING.md" />
        <File name="LICENSE" src="html/bower_components/angular-ui-router/LICENSE" />
        <File name="README" src="html/bower_components/angular-ui-router/README.md" />
        <File name="angular-ui-router.d" src="html/bower_components/angular-ui-router/api/angular-ui-router.d.ts" />
        <File name="bower" src="html/bower_components/angular-ui-router/bower.json" />
        <File name="angular-ui-router" src="html/bower_components/angular-ui-router/release/angular-ui-router.js" />
        <File name="angular-ui-router.min" src="html/bower_components/angular-ui-router/release/angular-ui-router.min.js" />
        <File name="common" src="html/bower_components/angular-ui-router/src/common.js" />
        <File name="resolve" src="html/bower_components/angular-ui-router/src/resolve.js" />
        <File name="state" src="html/bower_components/angular-ui-router/src/state.js" />
        <File name="stateDirectives" src="html/bower_components/angular-ui-router/src/stateDirectives.js" />
        <File name="stateFilters" src="html/bower_components/angular-ui-router/src/stateFilters.js" />
        <File name="templateFactory" src="html/bower_components/angular-ui-router/src/templateFactory.js" />
        <File name="urlMatcherFactory" src="html/bower_components/angular-ui-router/src/urlMatcherFactory.js" />
        <File name="urlRouter" src="html/bower_components/angular-ui-router/src/urlRouter.js" />
        <File name="view" src="html/bower_components/angular-ui-router/src/view.js" />
        <File name="viewDirective" src="html/bower_components/angular-ui-router/src/viewDirective.js" />
        <File name="viewScroll" src="html/bower_components/angular-ui-router/src/viewScroll.js" />
        <File name=".bower" src="html/bower_components/angular/.bower.json" />
        <File name="README" src="html/bower_components/angular/README.md" />
        <File name="angular-csp" src="html/bower_components/angular/angular-csp.css" />
        <File name="angular" src="html/bower_components/angular/angular.js" />
        <File name="angular.min" src="html/bower_components/angular/angular.min.js" />
        <File name="angular.min.js" src="html/bower_components/angular/angular.min.js.gzip" />
        <File name="angular.min.js" src="html/bower_components/angular/angular.min.js.map" />
        <File name="bower" src="html/bower_components/angular/bower.json" />
        <File name="index" src="html/bower_components/angular/index.js" />
        <File name="package" src="html/bower_components/angular/package.json" />
        <File name=".bower" src="html/bower_components/fastclick/.bower.json" />
        <File name="LICENSE" src="html/bower_components/fastclick/LICENSE" />
        <File name="README" src="html/bower_components/fastclick/README.md" />
        <File name="bower" src="html/bower_components/fastclick/bower.json" />
        <File name="fastclick" src="html/bower_components/fastclick/lib/fastclick.js" />
        <File name=".bower" src="html/bower_components/foundation/.bower.json" />
        <File name="bower" src="html/bower_components/foundation/bower.json" />
        <File name="foundation" src="html/bower_components/foundation/css/foundation.css" />
        <File name="foundation.css" src="html/bower_components/foundation/css/foundation.css.map" />
        <File name="normalize" src="html/bower_components/foundation/css/normalize.css" />
        <File name="normalize.css" src="html/bower_components/foundation/css/normalize.css.map" />
        <File name="foundation" src="html/bower_components/foundation/js/foundation.js" />
        <File name="foundation.min" src="html/bower_components/foundation/js/foundation.min.js" />
        <File name="foundation.abide" src="html/bower_components/foundation/js/foundation/foundation.abide.js" />
        <File name="foundation.accordion" src="html/bower_components/foundation/js/foundation/foundation.accordion.js" />
        <File name="foundation.alert" src="html/bower_components/foundation/js/foundation/foundation.alert.js" />
        <File name="foundation.clearing" src="html/bower_components/foundation/js/foundation/foundation.clearing.js" />
        <File name="foundation.dropdown" src="html/bower_components/foundation/js/foundation/foundation.dropdown.js" />
        <File name="foundation.equalizer" src="html/bower_components/foundation/js/foundation/foundation.equalizer.js" />
        <File name="foundation.interchange" src="html/bower_components/foundation/js/foundation/foundation.interchange.js" />
        <File name="foundation.joyride" src="html/bower_components/foundation/js/foundation/foundation.joyride.js" />
        <File name="foundation" src="html/bower_components/foundation/js/foundation/foundation.js" />
        <File name="foundation.magellan" src="html/bower_components/foundation/js/foundation/foundation.magellan.js" />
        <File name="foundation.offcanvas" src="html/bower_components/foundation/js/foundation/foundation.offcanvas.js" />
        <File name="foundation.orbit" src="html/bower_components/foundation/js/foundation/foundation.orbit.js" />
        <File name="foundation.reveal" src="html/bower_components/foundation/js/foundation/foundation.reveal.js" />
        <File name="foundation.slider" src="html/bower_components/foundation/js/foundation/foundation.slider.js" />
        <File name="foundation.tab" src="html/bower_components/foundation/js/foundation/foundation.tab.js" />
        <File name="foundation.tooltip" src="html/bower_components/foundation/js/foundation/foundation.tooltip.js" />
        <File name="foundation.topbar" src="html/bower_components/foundation/js/foundation/foundation.topbar.js" />
        <File name="fastclick" src="html/bower_components/foundation/js/vendor/fastclick.js" />
        <File name="jquery.cookie" src="html/bower_components/foundation/js/vendor/jquery.cookie.js" />
        <File name="jquery" src="html/bower_components/foundation/js/vendor/jquery.js" />
        <File name="modernizr" src="html/bower_components/foundation/js/vendor/modernizr.js" />
        <File name="placeholder" src="html/bower_components/foundation/js/vendor/placeholder.js" />
        <File name="foundation" src="html/bower_components/foundation/scss/foundation.scss" />
        <File name="_functions" src="html/bower_components/foundation/scss/foundation/_functions.scss" />
        <File name="_settings" src="html/bower_components/foundation/scss/foundation/_settings.scss" />
        <File name="_accordion" src="html/bower_components/foundation/scss/foundation/components/_accordion.scss" />
        <File name="_alert-boxes" src="html/bower_components/foundation/scss/foundation/components/_alert-boxes.scss" />
        <File name="_block-grid" src="html/bower_components/foundation/scss/foundation/components/_block-grid.scss" />
        <File name="_breadcrumbs" src="html/bower_components/foundation/scss/foundation/components/_breadcrumbs.scss" />
        <File name="_button-groups" src="html/bower_components/foundation/scss/foundation/components/_button-groups.scss" />
        <File name="_buttons" src="html/bower_components/foundation/scss/foundation/components/_buttons.scss" />
        <File name="_clearing" src="html/bower_components/foundation/scss/foundation/components/_clearing.scss" />
        <File name="_dropdown-buttons" src="html/bower_components/foundation/scss/foundation/components/_dropdown-buttons.scss" />
        <File name="_dropdown" src="html/bower_components/foundation/scss/foundation/components/_dropdown.scss" />
        <File name="_flex-video" src="html/bower_components/foundation/scss/foundation/components/_flex-video.scss" />
        <File name="_forms" src="html/bower_components/foundation/scss/foundation/components/_forms.scss" />
        <File name="_global" src="html/bower_components/foundation/scss/foundation/components/_global.scss" />
        <File name="_grid" src="html/bower_components/foundation/scss/foundation/components/_grid.scss" />
        <File name="_icon-bar" src="html/bower_components/foundation/scss/foundation/components/_icon-bar.scss" />
        <File name="_inline-lists" src="html/bower_components/foundation/scss/foundation/components/_inline-lists.scss" />
        <File name="_joyride" src="html/bower_components/foundation/scss/foundation/components/_joyride.scss" />
        <File name="_keystrokes" src="html/bower_components/foundation/scss/foundation/components/_keystrokes.scss" />
        <File name="_labels" src="html/bower_components/foundation/scss/foundation/components/_labels.scss" />
        <File name="_magellan" src="html/bower_components/foundation/scss/foundation/components/_magellan.scss" />
        <File name="_offcanvas" src="html/bower_components/foundation/scss/foundation/components/_offcanvas.scss" />
        <File name="_orbit" src="html/bower_components/foundation/scss/foundation/components/_orbit.scss" />
        <File name="_pagination" src="html/bower_components/foundation/scss/foundation/components/_pagination.scss" />
        <File name="_panels" src="html/bower_components/foundation/scss/foundation/components/_panels.scss" />
        <File name="_pricing-tables" src="html/bower_components/foundation/scss/foundation/components/_pricing-tables.scss" />
        <File name="_progress-bars" src="html/bower_components/foundation/scss/foundation/components/_progress-bars.scss" />
        <File name="_range-slider" src="html/bower_components/foundation/scss/foundation/components/_range-slider.scss" />
        <File name="_reveal" src="html/bower_components/foundation/scss/foundation/components/_reveal.scss" />
        <File name="_side-nav" src="html/bower_components/foundation/scss/foundation/components/_side-nav.scss" />
        <File name="_split-buttons" src="html/bower_components/foundation/scss/foundation/components/_split-buttons.scss" />
        <File name="_sub-nav" src="html/bower_components/foundation/scss/foundation/components/_sub-nav.scss" />
        <File name="_switches" src="html/bower_components/foundation/scss/foundation/components/_switches.scss" />
        <File name="_tables" src="html/bower_components/foundation/scss/foundation/components/_tables.scss" />
        <File name="_tabs" src="html/bower_components/foundation/scss/foundation/components/_tabs.scss" />
        <File name="_thumbs" src="html/bower_components/foundation/scss/foundation/components/_thumbs.scss" />
        <File name="_toolbar" src="html/bower_components/foundation/scss/foundation/components/_toolbar.scss" />
        <File name="_tooltips" src="html/bower_components/foundation/scss/foundation/components/_tooltips.scss" />
        <File name="_top-bar" src="html/bower_components/foundation/scss/foundation/components/_top-bar.scss" />
        <File name="_type" src="html/bower_components/foundation/scss/foundation/components/_type.scss" />
        <File name="_visibility" src="html/bower_components/foundation/scss/foundation/components/_visibility.scss" />
        <File name="normalize" src="html/bower_components/foundation/scss/normalize.scss" />
        <File name=".bower" src="html/bower_components/jquery-placeholder/.bower.json" />
        <File name="bower" src="html/bower_components/jquery-placeholder/bower.json" />
        <File name="jquery.placeholder" src="html/bower_components/jquery-placeholder/jquery.placeholder.js" />
        <File name=".bower" src="html/bower_components/jquery.cookie/.bower.json" />
        <File name="bower" src="html/bower_components/jquery.cookie/bower.json" />
        <File name="jquery.cookie" src="html/bower_components/jquery.cookie/jquery.cookie.js" />
        <File name=".bower" src="html/bower_components/jquery/.bower.json" />
        <File name="MIT-LICENSE" src="html/bower_components/jquery/MIT-LICENSE.txt" />
        <File name="bower" src="html/bower_components/jquery/bower.json" />
        <File name="jquery" src="html/bower_components/jquery/dist/jquery.js" />
        <File name="jquery.min" src="html/bower_components/jquery/dist/jquery.min.js" />
        <File name="jquery.min" src="html/bower_components/jquery/dist/jquery.min.map" />
        <File name="ajax" src="html/bower_components/jquery/src/ajax.js" />
        <File name="jsonp" src="html/bower_components/jquery/src/ajax/jsonp.js" />
        <File name="load" src="html/bower_components/jquery/src/ajax/load.js" />
        <File name="parseJSON" src="html/bower_components/jquery/src/ajax/parseJSON.js" />
        <File name="parseXML" src="html/bower_components/jquery/src/ajax/parseXML.js" />
        <File name="script" src="html/bower_components/jquery/src/ajax/script.js" />
        <File name="nonce" src="html/bower_components/jquery/src/ajax/var/nonce.js" />
        <File name="rquery" src="html/bower_components/jquery/src/ajax/var/rquery.js" />
        <File name="xhr" src="html/bower_components/jquery/src/ajax/xhr.js" />
        <File name="attributes" src="html/bower_components/jquery/src/attributes.js" />
        <File name="attr" src="html/bower_components/jquery/src/attributes/attr.js" />
        <File name="classes" src="html/bower_components/jquery/src/attributes/classes.js" />
        <File name="prop" src="html/bower_components/jquery/src/attributes/prop.js" />
        <File name="support" src="html/bower_components/jquery/src/attributes/support.js" />
        <File name="val" src="html/bower_components/jquery/src/attributes/val.js" />
        <File name="callbacks" src="html/bower_components/jquery/src/callbacks.js" />
        <File name="core" src="html/bower_components/jquery/src/core.js" />
        <File name="access" src="html/bower_components/jquery/src/core/access.js" />
        <File name="init" src="html/bower_components/jquery/src/core/init.js" />
        <File name="parseHTML" src="html/bower_components/jquery/src/core/parseHTML.js" />
        <File name="ready" src="html/bower_components/jquery/src/core/ready.js" />
        <File name="rsingleTag" src="html/bower_components/jquery/src/core/var/rsingleTag.js" />
        <File name="css" src="html/bower_components/jquery/src/css.js" />
        <File name="addGetHookIf" src="html/bower_components/jquery/src/css/addGetHookIf.js" />
        <File name="curCSS" src="html/bower_components/jquery/src/css/curCSS.js" />
        <File name="defaultDisplay" src="html/bower_components/jquery/src/css/defaultDisplay.js" />
        <File name="hiddenVisibleSelectors" src="html/bower_components/jquery/src/css/hiddenVisibleSelectors.js" />
        <File name="support" src="html/bower_components/jquery/src/css/support.js" />
        <File name="swap" src="html/bower_components/jquery/src/css/swap.js" />
        <File name="cssExpand" src="html/bower_components/jquery/src/css/var/cssExpand.js" />
        <File name="getStyles" src="html/bower_components/jquery/src/css/var/getStyles.js" />
        <File name="isHidden" src="html/bower_components/jquery/src/css/var/isHidden.js" />
        <File name="rmargin" src="html/bower_components/jquery/src/css/var/rmargin.js" />
        <File name="rnumnonpx" src="html/bower_components/jquery/src/css/var/rnumnonpx.js" />
        <File name="data" src="html/bower_components/jquery/src/data.js" />
        <File name="Data" src="html/bower_components/jquery/src/data/Data.js" />
        <File name="accepts" src="html/bower_components/jquery/src/data/accepts.js" />
        <File name="data_priv" src="html/bower_components/jquery/src/data/var/data_priv.js" />
        <File name="data_user" src="html/bower_components/jquery/src/data/var/data_user.js" />
        <File name="deferred" src="html/bower_components/jquery/src/deferred.js" />
        <File name="deprecated" src="html/bower_components/jquery/src/deprecated.js" />
        <File name="dimensions" src="html/bower_components/jquery/src/dimensions.js" />
        <File name="effects" src="html/bower_components/jquery/src/effects.js" />
        <File name="Tween" src="html/bower_components/jquery/src/effects/Tween.js" />
        <File name="animatedSelector" src="html/bower_components/jquery/src/effects/animatedSelector.js" />
        <File name="event" src="html/bower_components/jquery/src/event.js" />
        <File name="ajax" src="html/bower_components/jquery/src/event/ajax.js" />
        <File name="alias" src="html/bower_components/jquery/src/event/alias.js" />
        <File name="support" src="html/bower_components/jquery/src/event/support.js" />
        <File name="amd" src="html/bower_components/jquery/src/exports/amd.js" />
        <File name="global" src="html/bower_components/jquery/src/exports/global.js" />
        <File name="intro" src="html/bower_components/jquery/src/intro.js" />
        <File name="jquery" src="html/bower_components/jquery/src/jquery.js" />
        <File name="manipulation" src="html/bower_components/jquery/src/manipulation.js" />
        <File name="_evalUrl" src="html/bower_components/jquery/src/manipulation/_evalUrl.js" />
        <File name="support" src="html/bower_components/jquery/src/manipulation/support.js" />
        <File name="rcheckableType" src="html/bower_components/jquery/src/manipulation/var/rcheckableType.js" />
        <File name="offset" src="html/bower_components/jquery/src/offset.js" />
        <File name="outro" src="html/bower_components/jquery/src/outro.js" />
        <File name="queue" src="html/bower_components/jquery/src/queue.js" />
        <File name="delay" src="html/bower_components/jquery/src/queue/delay.js" />
        <File name="selector-native" src="html/bower_components/jquery/src/selector-native.js" />
        <File name="selector-sizzle" src="html/bower_components/jquery/src/selector-sizzle.js" />
        <File name="selector" src="html/bower_components/jquery/src/selector.js" />
        <File name="serialize" src="html/bower_components/jquery/src/serialize.js" />
        <File name="sizzle" src="html/bower_components/jquery/src/sizzle/dist/sizzle.js" />
        <File name="sizzle.min" src="html/bower_components/jquery/src/sizzle/dist/sizzle.min.js" />
        <File name="sizzle.min" src="html/bower_components/jquery/src/sizzle/dist/sizzle.min.map" />
        <File name="traversing" src="html/bower_components/jquery/src/traversing.js" />
        <File name="findFilter" src="html/bower_components/jquery/src/traversing/findFilter.js" />
        <File name="rneedsContext" src="html/bower_components/jquery/src/traversing/var/rneedsContext.js" />
        <File name="arr" src="html/bower_components/jquery/src/var/arr.js" />
        <File name="class2type" src="html/bower_components/jquery/src/var/class2type.js" />
        <File name="concat" src="html/bower_components/jquery/src/var/concat.js" />
        <File name="hasOwn" src="html/bower_components/jquery/src/var/hasOwn.js" />
        <File name="indexOf" src="html/bower_components/jquery/src/var/indexOf.js" />
        <File name="pnum" src="html/bower_components/jquery/src/var/pnum.js" />
        <File name="push" src="html/bower_components/jquery/src/var/push.js" />
        <File name="rnotwhite" src="html/bower_components/jquery/src/var/rnotwhite.js" />
        <File name="slice" src="html/bower_components/jquery/src/var/slice.js" />
        <File name="strundefined" src="html/bower_components/jquery/src/var/strundefined.js" />
        <File name="support" src="html/bower_components/jquery/src/var/support.js" />
        <File name="toString" src="html/bower_components/jquery/src/var/toString.js" />
        <File name="wrap" src="html/bower_components/jquery/src/wrap.js" />
        <File name=".bower" src="html/bower_components/modernizr/.bower.json" />
        <File name="" src="html/bower_components/modernizr/.editorconfig" />
        <File name="" src="html/bower_components/modernizr/.gitignore" />
        <File name=".travis" src="html/bower_components/modernizr/.travis.yml" />
        <File name="a-download" src="html/bower_components/modernizr/feature-detects/a-download.js" />
        <File name="audio-audiodata-api" src="html/bower_components/modernizr/feature-detects/audio-audiodata-api.js" />
        <File name="audio-webaudio-api" src="html/bower_components/modernizr/feature-detects/audio-webaudio-api.js" />
        <File name="battery-api" src="html/bower_components/modernizr/feature-detects/battery-api.js" />
        <File name="battery-level" src="html/bower_components/modernizr/feature-detects/battery-level.js" />
        <File name="blob-constructor" src="html/bower_components/modernizr/feature-detects/blob-constructor.js" />
        <File name="canvas-todataurl-type" src="html/bower_components/modernizr/feature-detects/canvas-todataurl-type.js" />
        <File name="contenteditable" src="html/bower_components/modernizr/feature-detects/contenteditable.js" />
        <File name="contentsecuritypolicy" src="html/bower_components/modernizr/feature-detects/contentsecuritypolicy.js" />
        <File name="contextmenu" src="html/bower_components/modernizr/feature-detects/contextmenu.js" />
        <File name="cookies" src="html/bower_components/modernizr/feature-detects/cookies.js" />
        <File name="cors" src="html/bower_components/modernizr/feature-detects/cors.js" />
        <File name="css-backgroundposition-shorthand" src="html/bower_components/modernizr/feature-detects/css-backgroundposition-shorthand.js" />
        <File name="css-backgroundposition-xy" src="html/bower_components/modernizr/feature-detects/css-backgroundposition-xy.js" />
        <File name="css-backgroundrepeat" src="html/bower_components/modernizr/feature-detects/css-backgroundrepeat.js" />
        <File name="css-backgroundsizecover" src="html/bower_components/modernizr/feature-detects/css-backgroundsizecover.js" />
        <File name="css-boxsizing" src="html/bower_components/modernizr/feature-detects/css-boxsizing.js" />
        <File name="css-calc" src="html/bower_components/modernizr/feature-detects/css-calc.js" />
        <File name="css-cubicbezierrange" src="html/bower_components/modernizr/feature-detects/css-cubicbezierrange.js" />
        <File name="css-displayrunin" src="html/bower_components/modernizr/feature-detects/css-displayrunin.js" />
        <File name="css-displaytable" src="html/bower_components/modernizr/feature-detects/css-displaytable.js" />
        <File name="css-filters" src="html/bower_components/modernizr/feature-detects/css-filters.js" />
        <File name="css-hyphens" src="html/bower_components/modernizr/feature-detects/css-hyphens.js" />
        <File name="css-lastchild" src="html/bower_components/modernizr/feature-detects/css-lastchild.js" />
        <File name="css-mask" src="html/bower_components/modernizr/feature-detects/css-mask.js" />
        <File name="css-mediaqueries" src="html/bower_components/modernizr/feature-detects/css-mediaqueries.js" />
        <File name="css-objectfit" src="html/bower_components/modernizr/feature-detects/css-objectfit.js" />
        <File name="css-overflow-scrolling" src="html/bower_components/modernizr/feature-detects/css-overflow-scrolling.js" />
        <File name="css-pointerevents" src="html/bower_components/modernizr/feature-detects/css-pointerevents.js" />
        <File name="css-positionsticky" src="html/bower_components/modernizr/feature-detects/css-positionsticky.js" />
        <File name="css-regions" src="html/bower_components/modernizr/feature-detects/css-regions.js" />
        <File name="css-remunit" src="html/bower_components/modernizr/feature-detects/css-remunit.js" />
        <File name="css-resize" src="html/bower_components/modernizr/feature-detects/css-resize.js" />
        <File name="css-scrollbars" src="html/bower_components/modernizr/feature-detects/css-scrollbars.js" />
        <File name="css-shapes" src="html/bower_components/modernizr/feature-detects/css-shapes.js" />
        <File name="css-subpixelfont" src="html/bower_components/modernizr/feature-detects/css-subpixelfont.js" />
        <File name="css-supports" src="html/bower_components/modernizr/feature-detects/css-supports.js" />
        <File name="css-userselect" src="html/bower_components/modernizr/feature-detects/css-userselect.js" />
        <File name="css-vhunit" src="html/bower_components/modernizr/feature-detects/css-vhunit.js" />
        <File name="css-vmaxunit" src="html/bower_components/modernizr/feature-detects/css-vmaxunit.js" />
        <File name="css-vminunit" src="html/bower_components/modernizr/feature-detects/css-vminunit.js" />
        <File name="css-vwunit" src="html/bower_components/modernizr/feature-detects/css-vwunit.js" />
        <File name="custom-protocol-handler" src="html/bower_components/modernizr/feature-detects/custom-protocol-handler.js" />
        <File name="dart" src="html/bower_components/modernizr/feature-detects/dart.js" />
        <File name="dataview-api" src="html/bower_components/modernizr/feature-detects/dataview-api.js" />
        <File name="dom-classlist" src="html/bower_components/modernizr/feature-detects/dom-classlist.js" />
        <File name="dom-createElement-attrs" src="html/bower_components/modernizr/feature-detects/dom-createElement-attrs.js" />
        <File name="dom-dataset" src="html/bower_components/modernizr/feature-detects/dom-dataset.js" />
        <File name="dom-microdata" src="html/bower_components/modernizr/feature-detects/dom-microdata.js" />
        <File name="elem-datalist" src="html/bower_components/modernizr/feature-detects/elem-datalist.js" />
        <File name="elem-details" src="html/bower_components/modernizr/feature-detects/elem-details.js" />
        <File name="elem-output" src="html/bower_components/modernizr/feature-detects/elem-output.js" />
        <File name="elem-progress-meter" src="html/bower_components/modernizr/feature-detects/elem-progress-meter.js" />
        <File name="elem-ruby" src="html/bower_components/modernizr/feature-detects/elem-ruby.js" />
        <File name="elem-time" src="html/bower_components/modernizr/feature-detects/elem-time.js" />
        <File name="elem-track" src="html/bower_components/modernizr/feature-detects/elem-track.js" />
        <File name="emoji" src="html/bower_components/modernizr/feature-detects/emoji.js" />
        <File name="es5-strictmode" src="html/bower_components/modernizr/feature-detects/es5-strictmode.js" />
        <File name="event-deviceorientation-motion" src="html/bower_components/modernizr/feature-detects/event-deviceorientation-motion.js" />
        <File name="exif-orientation" src="html/bower_components/modernizr/feature-detects/exif-orientation.js" />
        <File name="file-api" src="html/bower_components/modernizr/feature-detects/file-api.js" />
        <File name="file-filesystem" src="html/bower_components/modernizr/feature-detects/file-filesystem.js" />
        <File name="forms-fileinput" src="html/bower_components/modernizr/feature-detects/forms-fileinput.js" />
        <File name="forms-formattribute" src="html/bower_components/modernizr/feature-detects/forms-formattribute.js" />
        <File name="forms-inputnumber-l10n" src="html/bower_components/modernizr/feature-detects/forms-inputnumber-l10n.js" />
        <File name="forms-placeholder" src="html/bower_components/modernizr/feature-detects/forms-placeholder.js" />
        <File name="forms-speechinput" src="html/bower_components/modernizr/feature-detects/forms-speechinput.js" />
        <File name="forms-validation" src="html/bower_components/modernizr/feature-detects/forms-validation.js" />
        <File name="fullscreen-api" src="html/bower_components/modernizr/feature-detects/fullscreen-api.js" />
        <File name="gamepad" src="html/bower_components/modernizr/feature-detects/gamepad.js" />
        <File name="getusermedia" src="html/bower_components/modernizr/feature-detects/getusermedia.js" />
        <File name="ie8compat" src="html/bower_components/modernizr/feature-detects/ie8compat.js" />
        <File name="iframe-sandbox" src="html/bower_components/modernizr/feature-detects/iframe-sandbox.js" />
        <File name="iframe-seamless" src="html/bower_components/modernizr/feature-detects/iframe-seamless.js" />
        <File name="iframe-srcdoc" src="html/bower_components/modernizr/feature-detects/iframe-srcdoc.js" />
        <File name="img-apng" src="html/bower_components/modernizr/feature-detects/img-apng.js" />
        <File name="img-webp" src="html/bower_components/modernizr/feature-detects/img-webp.js" />
        <File name="json" src="html/bower_components/modernizr/feature-detects/json.js" />
        <File name="lists-reversed" src="html/bower_components/modernizr/feature-detects/lists-reversed.js" />
        <File name="mathml" src="html/bower_components/modernizr/feature-detects/mathml.js" />
        <File name="network-connection" src="html/bower_components/modernizr/feature-detects/network-connection.js" />
        <File name="network-eventsource" src="html/bower_components/modernizr/feature-detects/network-eventsource.js" />
        <File name="network-xhr2" src="html/bower_components/modernizr/feature-detects/network-xhr2.js" />
        <File name="notification" src="html/bower_components/modernizr/feature-detects/notification.js" />
        <File name="performance" src="html/bower_components/modernizr/feature-detects/performance.js" />
        <File name="pointerlock-api" src="html/bower_components/modernizr/feature-detects/pointerlock-api.js" />
        <File name="quota-management-api" src="html/bower_components/modernizr/feature-detects/quota-management-api.js" />
        <File name="requestanimationframe" src="html/bower_components/modernizr/feature-detects/requestanimationframe.js" />
        <File name="script-async" src="html/bower_components/modernizr/feature-detects/script-async.js" />
        <File name="script-defer" src="html/bower_components/modernizr/feature-detects/script-defer.js" />
        <File name="style-scoped" src="html/bower_components/modernizr/feature-detects/style-scoped.js" />
        <File name="svg-filters" src="html/bower_components/modernizr/feature-detects/svg-filters.js" />
        <File name="unicode" src="html/bower_components/modernizr/feature-detects/unicode.js" />
        <File name="url-data-uri" src="html/bower_components/modernizr/feature-detects/url-data-uri.js" />
        <File name="userdata" src="html/bower_components/modernizr/feature-detects/userdata.js" />
        <File name="vibration" src="html/bower_components/modernizr/feature-detects/vibration.js" />
        <File name="web-intents" src="html/bower_components/modernizr/feature-detects/web-intents.js" />
        <File name="webgl-extensions" src="html/bower_components/modernizr/feature-detects/webgl-extensions.js" />
        <File name="websockets-binary" src="html/bower_components/modernizr/feature-detects/websockets-binary.js" />
        <File name="window-framed" src="html/bower_components/modernizr/feature-detects/window-framed.js" />
        <File name="workers-blobworkers" src="html/bower_components/modernizr/feature-detects/workers-blobworkers.js" />
        <File name="workers-dataworkers" src="html/bower_components/modernizr/feature-detects/workers-dataworkers.js" />
        <File name="workers-sharedworkers" src="html/bower_components/modernizr/feature-detects/workers-sharedworkers.js" />
        <File name="grunt" src="html/bower_components/modernizr/grunt.js" />
        <File name="Modernizr 2 Logo" src="html/bower_components/modernizr/media/Modernizr 2 Logo.ai" />
        <File name="Modernizr 2 Logo" src="html/bower_components/modernizr/media/Modernizr 2 Logo.eps" />
        <File name="Modernizr 2 Logo" src="html/bower_components/modernizr/media/Modernizr 2 Logo.pdf" />
        <File name="Modernizr 2 Logo" src="html/bower_components/modernizr/media/Modernizr 2 Logo.png" />
        <File name="Modernizr 2 Logo" src="html/bower_components/modernizr/media/Modernizr 2 Logo.svg" />
        <File name="modernizr" src="html/bower_components/modernizr/modernizr.js" />
        <File name="readme" src="html/bower_components/modernizr/readme.md" />
        <File name="basic" src="html/bower_components/modernizr/test/basic.html" />
        <File name="caniuse" src="html/bower_components/modernizr/test/caniuse.html" />
        <File name="Windsong-webfont" src="html/bower_components/modernizr/test/caniuse_files/Windsong-webfont.eot" />
        <File name="Windsong-webfont" src="html/bower_components/modernizr/test/caniuse_files/Windsong-webfont.otf" />
        <File name="Windsong-webfont" src="html/bower_components/modernizr/test/caniuse_files/Windsong-webfont.svg" />
        <File name="Windsong-webfont" src="html/bower_components/modernizr/test/caniuse_files/Windsong-webfont.ttf" />
        <File name="Windsong-webfont" src="html/bower_components/modernizr/test/caniuse_files/Windsong-webfont.woff" />
        <File name="alpha" src="html/bower_components/modernizr/test/caniuse_files/alpha.png" />
        <File name="apng_test" src="html/bower_components/modernizr/test/caniuse_files/apng_test.png" />
        <File name="before-after" src="html/bower_components/modernizr/test/caniuse_files/before-after.png" />
        <File name="form_validation" src="html/bower_components/modernizr/test/caniuse_files/form_validation.html" />
        <File name="ga" src="html/bower_components/modernizr/test/caniuse_files/ga.js" />
        <File name="green5x5" src="html/bower_components/modernizr/test/caniuse_files/green5x5.png" />
        <File name="hashchange" src="html/bower_components/modernizr/test/caniuse_files/hashchange.html" />
        <File name="jquery.min" src="html/bower_components/modernizr/test/caniuse_files/jquery.min.js" />
        <File name="mathml" src="html/bower_components/modernizr/test/caniuse_files/mathml.html" />
        <File name="mathml_ref" src="html/bower_components/modernizr/test/caniuse_files/mathml_ref.png" />
        <File name="modernizr-1.7.min" src="html/bower_components/modernizr/test/caniuse_files/modernizr-1.7.min.js" />
        <File name="png_alpha_result" src="html/bower_components/modernizr/test/caniuse_files/png_alpha_result.png" />
        <File name="pushstate" src="html/bower_components/modernizr/test/caniuse_files/pushstate.html" />
        <File name="red30x30" src="html/bower_components/modernizr/test/caniuse_files/red30x30.png" />
        <File name="ruby" src="html/bower_components/modernizr/test/caniuse_files/ruby.png" />
        <File name="stroked-text" src="html/bower_components/modernizr/test/caniuse_files/stroked-text.png" />
        <File name="style" src="html/bower_components/modernizr/test/caniuse_files/style.css" />
        <File name="svg-html-blur" src="html/bower_components/modernizr/test/caniuse_files/svg-html-blur.png" />
        <File name="svg-img" src="html/bower_components/modernizr/test/caniuse_files/svg-img.svg" />
        <File name="svg-img.svg" src="html/bower_components/modernizr/test/caniuse_files/svg-img.svg.1" />
        <File name="svg_blur" src="html/bower_components/modernizr/test/caniuse_files/svg_blur.png" />
        <File name="table" src="html/bower_components/modernizr/test/caniuse_files/table.png" />
        <File name="text-shadow1" src="html/bower_components/modernizr/test/caniuse_files/text-shadow1.png" />
        <File name="text-shadow2" src="html/bower_components/modernizr/test/caniuse_files/text-shadow2.png" />
        <File name="windsong_font" src="html/bower_components/modernizr/test/caniuse_files/windsong_font.png" />
        <File name="xhtml" src="html/bower_components/modernizr/test/caniuse_files/xhtml.html" />
        <File name="index" src="html/bower_components/modernizr/test/index.html" />
        <File name="basic" src="html/bower_components/modernizr/test/js/basic.html" />
        <File name="dumpdata" src="html/bower_components/modernizr/test/js/dumpdata.js" />
        <File name="detect-global" src="html/bower_components/modernizr/test/js/lib/detect-global.js" />
        <File name="jquery-1.7b2" src="html/bower_components/modernizr/test/js/lib/jquery-1.7b2.js" />
        <File name="jsonselect" src="html/bower_components/modernizr/test/js/lib/jsonselect.js" />
        <File name="polyfills" src="html/bower_components/modernizr/test/js/lib/polyfills.js" />
        <File name="uaparser" src="html/bower_components/modernizr/test/js/lib/uaparser.js" />
        <File name="setup" src="html/bower_components/modernizr/test/js/setup.js" />
        <File name="unit-caniuse" src="html/bower_components/modernizr/test/js/unit-caniuse.js" />
        <File name="unit" src="html/bower_components/modernizr/test/js/unit.js" />
        <File name="qunit" src="html/bower_components/modernizr/test/qunit/qunit.css" />
        <File name="qunit" src="html/bower_components/modernizr/test/qunit/qunit.js" />
        <File name="run-qunit" src="html/bower_components/modernizr/test/qunit/run-qunit.js" />
        <File name="" src="html/.DS_Store" />
        <File name="Application" src="html/js/Application.ts" />
        <File name="_all" src="html/js/_all.ts" />
        <File name="app" src="html/js/app.js" />
        <File name="AnimationCtrl" src="html/js/controllers/AnimationCtrl.ts" />
        <File name="TodoCtrl" src="html/js/controllers/TodoCtrl.ts" />
        <File name="TopBarCtrl" src="html/js/controllers/TopBarCtrl.ts" />
        <File name="TodoBlur" src="html/js/directives/TodoBlur.ts" />
        <File name="TodoFocus" src="html/js/directives/TodoFocus.ts" />
        <File name="ITodoScope" src="html/js/interfaces/ITodoScope.ts" />
        <File name="ITodoStorage" src="html/js/interfaces/ITodoStorage.ts" />
        <File name="utils_debug" src="html/js/libs/utils_debug.js" />
        <File name="utils_services" src="html/js/libs/utils_services.js" />
        <File name="TodoItem" src="html/js/models/TodoItem.ts" />
        <File name="QiMessaging" src="html/js/services/QiMessaging.ts" />
        <File name="TodoStorage" src="html/js/services/TodoStorage.ts" />
        <File name=".bower" src="html/bower_components/socket.io-client/.bower.json" />
        <File name="" src="html/bower_components/socket.io-client/.gitignore" />
        <File name="" src="html/bower_components/socket.io-client/.npmignore" />
        <File name=".travis" src="html/bower_components/socket.io-client/.travis.yml" />
        <File name=".zuul" src="html/bower_components/socket.io-client/.zuul.yml" />
        <File name="History" src="html/bower_components/socket.io-client/History.md" />
        <File name="LICENSE" src="html/bower_components/socket.io-client/LICENSE" />
        <File name="Makefile" src="html/bower_components/socket.io-client/Makefile" />
        <File name="README" src="html/bower_components/socket.io-client/README.md" />
        <File name="index" src="html/bower_components/socket.io-client/index.js" />
        <File name="index" src="html/bower_components/socket.io-client/lib/index.js" />
        <File name="manager" src="html/bower_components/socket.io-client/lib/manager.js" />
        <File name="on" src="html/bower_components/socket.io-client/lib/on.js" />
        <File name="socket" src="html/bower_components/socket.io-client/lib/socket.js" />
        <File name="url" src="html/bower_components/socket.io-client/lib/url.js" />
        <File name="package" src="html/bower_components/socket.io-client/package.json" />
        <File name="socket.io" src="html/bower_components/socket.io-client/socket.io.js" />
        <File name="browserify" src="html/bower_components/socket.io-client/support/browserify.js" />
        <File name="browserify" src="html/bower_components/socket.io-client/support/browserify.sh" />
        <File name="connection" src="html/bower_components/socket.io-client/test/connection.js" />
        <File name="index" src="html/bower_components/socket.io-client/test/index.js" />
        <File name="socket" src="html/bower_components/socket.io-client/test/socket.js" />
        <File name="env" src="html/bower_components/socket.io-client/test/support/env.js" />
        <File name="server" src="html/bower_components/socket.io-client/test/support/server.js" />
        <File name="url" src="html/bower_components/socket.io-client/test/url.js" />
        <File name="qimessaging" src="html/js/libs/qimessaging.js" />
        <File name="MoveCtrl" src="html/js/controllers/MoveCtrl.ts" />
        <File name="SystemCtrl" src="html/js/controllers/SystemCtrl.ts" />
        <File name="" src="html/js/services/.DS_Store" />
        <File name=".bower" src="html/bower_components/angular-gestures/.bower.json" />
        <File name="LICENSE" src="html/bower_components/angular-gestures/LICENSE.md" />
        <File name="README" src="html/bower_components/angular-gestures/README.md" />
        <File name="bower" src="html/bower_components/angular-gestures/bower.json" />
        <File name="gestures" src="html/bower_components/angular-gestures/gestures.js" />
        <File name="gestures.min" src="html/bower_components/angular-gestures/gestures.min.js" />
        <File name=".bower" src="html/bower_components/hammerjs/.bower.json" />
        <File name="" src="html/bower_components/hammerjs/.bowerrc" />
        <File name="" src="html/bower_components/hammerjs/.gitignore" />
        <File name="" src="html/bower_components/hammerjs/.jscsrc" />
        <File name="" src="html/bower_components/hammerjs/.jshintrc" />
        <File name=".travis" src="html/bower_components/hammerjs/.travis.yml" />
        <File name="CHANGELOG" src="html/bower_components/hammerjs/CHANGELOG.md" />
        <File name="CONTRIBUTING" src="html/bower_components/hammerjs/CONTRIBUTING.md" />
        <File name="Gruntfile" src="html/bower_components/hammerjs/Gruntfile.coffee" />
        <File name="LICENSE" src="html/bower_components/hammerjs/LICENSE.md" />
        <File name="README" src="html/bower_components/hammerjs/README.md" />
        <File name="bower" src="html/bower_components/hammerjs/bower.json" />
        <File name="component" src="html/bower_components/hammerjs/component.json" />
        <File name="hammer" src="html/bower_components/hammerjs/hammer.js" />
        <File name="hammer.min" src="html/bower_components/hammerjs/hammer.min.js" />
        <File name="hammer.min" src="html/bower_components/hammerjs/hammer.min.map" />
        <File name="package" src="html/bower_components/hammerjs/package.json" />
        <File name="AnimationBehaviorItem" src="html/js/models/AnimationBehaviorItem.ts" />
        <File name="AnimationTabItem" src="html/js/models/AnimationTabItem.ts" />
        <File name="animation" src="html/views/animation.html" />
        <File name="move" src="html/views/move.html" />
        <File name="system" src="html/views/system.html" />
        <File name="miku" src="html/images/miku.png" />
        <File name="nico-tech" src="html/images/nico-tech.png" />
        <File name="TabletCtrl" src="html/js/controllers/TabletCtrl.ts" />
        <File name="tablet" src="html/views/tablet.html" />
        <File name="VoiceCtrl" src="html/js/controllers/VoiceCtrl.ts" />
        <File name="VoiceBehaviorItem" src="html/js/models/VoiceBehaviorItem.ts" />
        <File name="VoiceTabItem" src="html/js/models/VoiceTabItem.ts" />
        <File name="voice" src="html/views/voice.html" />
        <File name="nico-tech14-15" src="html/images/nico-tech14-15.png" />
    </Resources>
    <Topics />
    <IgnoredPaths />
</Package>
